"""empty message

Revision ID: 105f971e5891
Revises: 72cb4ff3a59c
Create Date: 2023-05-01 20:13:14.616483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '105f971e5891'
down_revision = '72cb4ff3a59c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interface')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interface',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('connection', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('infra_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('port_channel_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('max_frame_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['port_channel_id'], ['interface.id'], name='interface_port_channel_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='interface_pkey')
    )
    # ### end Alembic commands ###
