"""empty message

Revision ID: 72cb4ff3a59c
Revises: f18e7397ae18
Create Date: 2023-05-01 17:35:23.201938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '72cb4ff3a59c'
down_revision = 'f18e7397ae18'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
