"""empty message

Revision ID: 5c67c6b060df
Revises: 105f971e5891
Create Date: 2023-05-01 20:13:35.618240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c67c6b060df'
down_revision = '105f971e5891'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
